Issue/css grid fix
AntonSkovpen/to-do-list pull request #17
Opened 2018-07-05 09:32 UTC by Akilesgos

2018-07-05 18:50 UTC, d4ins submitted a review, later dismissed
Make changes marked in comments

2018-07-05 18:50 UTC, d4ins commented on src/containers/Authorization/index.js
> +      <Grid container alignItems={'center'} direction={'column'}>
This component is expecting string props as value.

Use curly braces `{}` to do escape JS code in attribute, if you need to add a string value - then you can pass this like this: `alignItems="center" direction="column"`. 

But be careful when you're working with number, if you will pass in props `<MyComponenet myProp="1" />` It will be a string and this compare will not work `myProp === 1 // false`. So only way to pass number is `<MyComponenet myProp={1} />`

2018-07-05 18:50 UTC, d4ins commented on src/containers/Authorization/index.js
>      name: 'Enter your name',
Name should be an empty string. Use placeholder to show text like this one. And this field must be used as default state value, in your case is empty string.

2018-07-05 18:50 UTC, d4ins commented on src/containers/Authorization/index.js
> +  password = 'example';
This computed value `password` is more like constant type value, it will never changed.

The best way to inform other developer that this is constant - is to use upcase.

So proper name for `password` will be `PASSWORD = 'example';`

2018-07-05 18:50 UTC, d4ins commented on src/containers/Authorization/index.js
>      const { classes } = this.props;
You can use distructurization to get values of `containerform`. But it will be okish you will not use distucturization here.

2018-07-05 18:50 UTC, d4ins commented on src/containers/ToDoList/index.js
> +        justify={'center'}
This you need to correct too.

2018-07-05 18:52 UTC, d4ins commented
Also, name of the branch is incorrect.

It should be `issue/14_css_grid_fix` or more in JS style `issue/14-css-grid-fix`

2018-07-06 23:03 UTC, Akilesgos commented on src/containers/Authorization/index.js
> +      <Grid container alignItems={'center'} direction={'column'}>
done

2018-07-06 23:03 UTC, Akilesgos commented on src/containers/Authorization/index.js
>      name: 'Enter your name',
done

2018-07-06 23:03 UTC, Akilesgos commented on src/containers/Authorization/index.js
> +  password = 'example';
done

2018-07-06 23:10 UTC, Akilesgos commented on src/containers/Authorization/index.js
>      const { classes } = this.props;
Andrey, thank you for new slang  word 'okish'. Also i think that use distructurization in this situation will be good idea , because it earlier to read the  code

2018-07-06 23:10 UTC, Akilesgos commented on src/containers/ToDoList/index.js
> +        justify={'center'}
done

2018-07-07 19:56 UTC, d4ins requested changes

2018-07-07 19:56 UTC, d4ins commented on package.json
> +    "universal-cookie": "^2.2.0"
I see you added in this issue cookies.

This is ruining idea of the PR workflow.

For each issue what was created you need to create separate branch.

So first of all you need to:
- [ ] rename this branch like so `issue/14-css-grid-fix`, there are some conventions in naming branches.
- [ ] move your cookies changes to separate branch

2018-07-07 19:56 UTC, d4ins commented on src/components/AddNewTaskToListButton/index.js
> +      onClick={() => addNewItem(inputValue)} //
Try not to live this `//` in your code - it must be clean

2018-07-07 19:56 UTC, d4ins commented on src/components/TaskOfTheList/index.js
> +    <List>{items.length > 0 && RenderTaskOfTheList(items, addNewStatus)}</List>
How this works? Is this a recursion of your component?

2018-07-07 19:56 UTC, d4ins commented on src/containers/Authorization/index.js
> +    if (cookies.get('cookieAccess')) {
Hm, don't break your logic, it should look like this:

`if (this.state.access || cookies.get('cookieAccess') {`

But personally i would prefer to move this to separate function, eg:

```
isAuthorized() {
  const { access } = this.state
  return access || cookies.get('cookeAccess')
}

render() {
  if (this.isAuthorized()) {
    redirectTo('...')
  }
}
```

2018-07-07 19:56 UTC, d4ins commented on src/containers/Authorization/index.js
> +                onChange={this.onLoginChange}
Add `placeholder` prop with `Enter your name` to keep you idea

2018-07-07 19:56 UTC, d4ins commented on src/containers/ToDoList/index.js
> +    if (cookies.get('cookieAccess') === undefined) {
You don't need such compare. Just do like this: `if (!cookies.get('cookieAccess')`

2018-07-15 17:09 UTC, merged